namespace Snap
{
    using NXOpen;
    using System;
    using System.Drawing.Printing;
    using System.Runtime.InteropServices;

    public static class Print
    {
        //public static void PrintDisplay(int copies = 1, double thinWidth = 1.0, double normalWidth = 2.0, double thickWidth = 3.0, PrintBuilder.OutputOption output = PrintBuilder.OutputOption.WireframeBlackWhite, bool whiteBackground = false, bool rasterImages = true, bool shadedGeometry = false, PrintBuilder.ImageResolutionOption imageResolutionOption = 0, PrintBuilder.OrientationOption orientation = 0, PrintBuilder.PaperSize paper = PrintBuilder.PaperSize.A4)
        //{
        //    PrintBuilder builder = Globals.WorkPart.NXOpenPart.PlotManager.CreatePrintBuilder();
        //    builder.Copies = copies;
        //    builder.ThinWidth = thinWidth;
        //    builder.NormalWidth = normalWidth;
        //    builder.ThickWidth = thickWidth;
        //    builder.Output = output;
        //    builder.RasterImages = rasterImages;
        //    builder.ShadedGeometry = shadedGeometry;
        //    builder.ImageResolution = imageResolutionOption;
        //    NXObject[] sheets = new NXObject[1];
        //    builder.SourceBuilder.SetSheets(sheets);
        //    PrintDocument document = new PrintDocument();
        //    builder.PrinterText = document.PrinterSettings.PrinterName;
        //    builder.WhiteBackground = whiteBackground;
        //    builder.Orientation = orientation;
        //    builder.Paper = paper;
        //    builder.Commit();
        //    builder.Destroy();
        //}
    }
}

